# configs

set-option global tabstop 2
set-option global indentwidth 2
add-highlighter global/ number-lines

# jj to escape 
hook global InsertChar j %{ try %{
  exec -draft hH <a-k>jj<ret> d
  exec <esc>
}}

# highlight current line
hook global WinCreate ^[^*]+$ %{ add-highlighter window/ number-lines -hlcursor }

# load plug
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# load plugins
source "%val{config}/plugins.kak"
